version: "3.11"

services:
  # Uncomment the gateway service if you have one.
  # gateway:
  #   build: ./gateway
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - products_service
  #     - employees_service

  products_service:
    build: ./services/products
    ports:
      - "8000:8000"
    volumes:
      - ./services/employees/app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/products_db
    depends_on:
      - db

  employees_service:
    build: ./services/employees
    ports:
      - "8001:8001"
    volumes:
      - ./services/products/app:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/products_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
